################################################################################
# Library registration
################################################################################
$(eval $(call addlib_s,libnettle,$(CONFIG_LIBNETTLE)))

################################################################################
# Original sources
################################################################################
LIBNETTLE_VERSION=4.0
LIBNETTLE_TARNAME=nettle-$(LIBNETTLE_VERSION)
LIBNETTLE_URL=https://ftp.gnu.org/gnu/nettle/$(LIBNETTLE_TARNAME).tar.gz
$(eval $(call fetch,libnettle,$(LIBNETTLE_URL)))
LIBNETTLE_PATCHDIR=$(LIBNETTLE_BASE)/patches
$(eval $(call patch,libnettle,$(LIBNETTLE_PATCHDIR),$(LIBNETTLE_TARNAME)))

################################################################################
# Helpers
################################################################################
LIBNETTLE_DIR = $(LIBNETTLE_ORIGIN)/$(LIBNETTLE_TARNAME)

################################################################################
# Library includes
################################################################################
LIBNETTLE-CINCLUDES-y = -I$(LIBNETTLE_DIR)

################################################################################
# Global flags
################################################################################
LIBNETTLE_CFLAGS = -DHAVE_CONFIG_H -g -O2 -ggdb3 -Wall -W -Wno-sign-compare   \
-Wno-missing-prototypes -Wno-missing-declarations -Wstrict-prototypes   \
-Wpointer-arith -Wbad-function-cast -Wnested-externs -fpic -MT $@ -MD -MP \
-MF $@.d

################################################################################
# Nettle code (pure c; assembly is disabled via ./configure --disable-assembler
# so the build is arch independent)
################################################################################
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes128-decrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes128-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes128-set-decrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes128-set-encrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes192-decrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes192-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes192-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes192-set-decrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes192-set-encrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes256-decrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes256-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes256-set-decrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes256-set-encrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-decrypt-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-decrypt-table.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-encrypt-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-encrypt-table.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-invert-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/aes-set-key-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/arcfour.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/arctwo.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/arctwo-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/balloon.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/balloon-sha1.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/balloon-sha256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/balloon-sha384.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/balloon-sha512.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base16-decode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base16-encode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base64-decode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base64-encode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base64url-decode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/base64url-encode.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/blowfish-bcrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/blowfish.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/buffer.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/buffer-init.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia128-crypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia128-set-decrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia128-set-encrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia192-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia256-crypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia256-set-decrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia256-set-encrypt-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia-absorb.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia-crypt-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia-invert-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/camellia-table.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cast128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cast128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cbc-aes128-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cbc-aes192-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cbc-aes256-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cbc.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ccm-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ccm-aes192.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ccm-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ccm.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cfb.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-core-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-crypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-poly1305.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-poly1305-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/chacha-set-nonce.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac64.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-aes128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-aes256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-des3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cmac-des3-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/cnd-memcpy.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ctr16.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ctr.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/des3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/des.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/drbg-ctr-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/eax-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/eax-aes128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/eax.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes192.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes192-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-aes256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-camellia128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-camellia128-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-camellia256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-camellia256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-sm4.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gcm-sm4-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ghash-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ghash-update.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gost28147.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gosthash94.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/gosthash94-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hkdf.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-gosthash94.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-gosthash94-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-md5.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-md5-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-ripemd160.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-ripemd160-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha1.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha1-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha224.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha224-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha384.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha384-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha512.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sha512-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sm3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-sm3-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-streebog.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/hmac-streebog-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/knuth-lfib.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md2.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md2-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md4.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md4-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md5.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/md5-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/memeql-sec.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/memxor3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/memxor.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nettle-lookup-hash.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nettle-meta-aeads.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nettle-meta-ciphers.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nettle-meta-hashes.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nettle-meta-macs.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/nist-keywrap.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ocb-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ocb.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2-hmac-gosthash94.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2-hmac-sha1.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2-hmac-sha256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2-hmac-sha384.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/pbkdf2-hmac-sha512.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/poly1305-aes.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/poly1305-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/poly1305-update.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/realloc.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ripemd160.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ripemd160-compress.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/ripemd160-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-128-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-256-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-core-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-crypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-crypt-internal.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20r12-crypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/salsa20-set-nonce.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/serpent-decrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/serpent-encrypt.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/serpent-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/serpent-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha1.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha1-compress.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha1-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha224-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha256-compress-n.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-224.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-224-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-384.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-384-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-512.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-512-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha384-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-permute.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha3-shake.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha512-224-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha512-256-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha512.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha512-compress.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sha512-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/shake128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/shake256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-cmac-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-cmac-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-cmac.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-gcm-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-gcm-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-gcm.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-ghash-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/siv-ghash-update.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-128f.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-128s.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-sha2-128f.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-sha2-128s.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-shake-128f.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-dsa-shake-128s.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-fors.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-merkle.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-sha256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-shake.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-wots.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/slh-xmss.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sm3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sm3-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sm4.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/sm4-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/streebog.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/streebog-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/twofish.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/twofish-meta.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac32.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac64.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac96.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-l2.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-l3.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-nh.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-nh-n.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-poly128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-poly64.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/umac-set-key.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/version.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/write-be32.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/write-le32.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/write-le64.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/xts-aes128.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/xts-aes256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/xts.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/yarrow256.c
LIBNETTLE_SRCS-y += $(LIBNETTLE_DIR)/yarrow_key_event.c

################################################################################
# Hogweed code (public-key crypto: RSA / ECDSA / EdDSA / DSA), built only when
# CONFIG_LIBNETTLE_HOGWEED is set. Bignums come from the bundled mini-gmp.
################################################################################
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/mini-gmp.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/bignum.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/bignum-random.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/bignum-random-prime.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/cnd-copy.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve25519-eh-to-x.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve25519-mul.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve25519-mul-g.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve448-eh-to-x.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve448-mul.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/curve448-mul-g.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/der2dsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/der2rsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/der-iterator.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa2sexp.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa-gen-params.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa-hash.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa-keygen.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/dsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-eh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-ehh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-jja.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-jjj.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-th.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-add-thh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-a-to-j.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-curve25519.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-curve448.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-dup-eh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-dup-jj.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-dup-th.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-ecdsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-ecdsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-eh-to-a.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-gostdsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-gostdsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-gost-gc256b.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-gost-gc512a.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-j-to-a.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mod-arith.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mod.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mod-inv.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mul-a.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mul-a-eh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mul-g.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mul-g-eh.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-mul-m.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-nonsec-add-jjj.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-pm1-redc.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-point.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-point-mul.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-point-mul-g.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-pp1-redc.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-random.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-scalar.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-secp192r1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-secp224r1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-secp256r1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-secp384r1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-secp521r1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecc-size.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecdsa-keygen.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecdsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ecdsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed25519-sha512.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed25519-sha512-pubkey.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed25519-sha512-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed25519-sha512-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed448-shake256.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed448-shake256-pubkey.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed448-shake256-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/ed448-shake256-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-compress.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-decompress.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-expand.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-hash.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-pubkey.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/eddsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/gmp-glue.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/gostdsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/gostdsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/gostdsa-vko.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/oaep.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-decrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-encrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-rsa-digest.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-rsa-md5.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-rsa-sha1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-rsa-sha256.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-rsa-sha512.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pkcs1-sec-decrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pss.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/pss-mgf1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa2sexp.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-decrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-decrypt-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-encrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-keygen.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-md5-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-md5-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-md5-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-oaep-decrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-oaep-encrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pkcs1-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pkcs1-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pkcs1-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pss-sha256-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pss-sha256-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pss-sha512-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-pss-sha512-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sec-compute-root.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sec-decrypt.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha1-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha1-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha1-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha256-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha256-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha256-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha512-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha512-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sha512-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sign.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-sign-tr.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/rsa-verify.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sec-add-1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sec-sub-1.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp2bignum.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp2dsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp2rsa.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp-format.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp-transport.c
LIBNETTLE_SRCS-$(CONFIG_LIBNETTLE_HOGWEED) += $(LIBNETTLE_DIR)/sexp-transport-format.c

################################################################################
# Nettle prepare
################################################################################
# Run ./configure. --enable-mini-gmp builds bignum support from source ; --disable-assembler keeps the
# build pure C and architecture-independent.
$(LIBNETTLE_DIR)/.configured: $(LIBNETTLE_BUILD)/.origin
	$(call verbose_cmd,CONFIG,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./configure --enable-mini-gmp --disable-assembler && touch $@ && cp config.h testsuite/)

# Expose headers under the canonical <nettle/...> include prefix via a
# self-referential symlink (consumers include <nettle/rsa.h>).
$(LIBNETTLE_DIR)/nettle: $(LIBNETTLE_DIR)/.configured
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ln -sfn . nettle)

# Host-built ECC table generator. eccdata.c #includes mini-gmp.c directly, so it
# is self-contained and built with the host compiler.
$(LIBNETTLE_DIR)/eccdata: $(LIBNETTLE_DIR)/.configured
	$(call verbose_cmd,HOSTCC,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && $(HOSTCC) -O eccdata.c -lm -o eccdata)

# Generated ECC curve tables (NUMB_BITS=64 for x86_64/arm64 mini-gmp limbs).
$(LIBNETTLE_DIR)/ecc-secp192r1.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata secp192r1 8 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-secp224r1.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata secp224r1 16 7 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-secp256r1.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata secp256r1 11 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-secp384r1.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata secp384r1 32 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-secp521r1.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata secp521r1 44 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-curve25519.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata curve25519 11 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-curve448.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata curve448 38 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-gost-gc256b.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata gost_gc256b 11 6 64 >$@T && mv $@T $@)
$(LIBNETTLE_DIR)/ecc-gost-gc512a.h: $(LIBNETTLE_DIR)/eccdata
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && ./eccdata gost_gc512a 43 6 64 >$@T && mv $@T $@)

LIBNETTLE_PREPARED_DEPS = \
	$(LIBNETTLE_DIR)/.configured \
	$(LIBNETTLE_DIR)/nettle

# Hogweed needs the eccdata-generated curve tables before any source compiles.
LIBNETTLE_PREPARED_DEPS-$(CONFIG_LIBNETTLE_HOGWEED) += \
	$(LIBNETTLE_DIR)/ecc-secp192r1.h \
	$(LIBNETTLE_DIR)/ecc-secp224r1.h \
	$(LIBNETTLE_DIR)/ecc-secp256r1.h \
	$(LIBNETTLE_DIR)/ecc-secp384r1.h \
	$(LIBNETTLE_DIR)/ecc-secp521r1.h \
	$(LIBNETTLE_DIR)/ecc-curve25519.h \
	$(LIBNETTLE_DIR)/ecc-curve448.h \
	$(LIBNETTLE_DIR)/ecc-gost-gc256b.h \
	$(LIBNETTLE_DIR)/ecc-gost-gc512a.h

$(LIBNETTLE_BUILD)/.prepared : $(LIBNETTLE_PREPARED_DEPS) $(LIBNETTLE_PREPARED_DEPS-y)
	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR) && touch $@)

UK_PREPARE += $(LIBNETTLE_BUILD)/.prepared
